// src/components/TheHeader/TheHeader.tsx
import styled from '@emotion/styled';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { FC, useCallback, useEffect, useRef } from 'react';
import { HiSearch } from 'react-icons/hi';

import { Logo } from '@/components/Logo';
import Search from '@/components/Search';
import { mobile } from '@/lib/mediaQuery';

const initUnpinHeader = (elHeader: HTMLElement) => {
  const headerHeight = elHeader.offsetHeight;
  const headerUnpinClassName = 'is-unpin';
  let ticking = false;
  let lastKnownScrollY = 0;

  const handleScroll = (elHeader: HTMLElement, headerHeight: number) => {
    if (!ticking) {
      requestAnimationFrame(() => {
        ticking = false;
        const currentScrollY = window.pageYOffset;

        // ヘッダーの高さを超えた場合
        if (currentScrollY >= headerHeight) {
          if (currentScrollY <= lastKnownScrollY) {
            elHeader.classList.remove(headerUnpinClassName);
          } else {
            elHeader.classList.add(headerUnpinClassName);
          }
        } else {
          elHeader.classList.remove(headerUnpinClassName);
        }

        // 今回のスクロール位置を残す
        lastKnownScrollY = currentScrollY;
      });
    }

    ticking = true;
  };

  document.addEventListener(
    'scroll',
    () => {
      handleScroll(elHeader, headerHeight);
    },
    { passive: true },
  );
};

export const TheHeader: FC = () => {
  const refDialog = useRef<HTMLDialogElement>(null);
  const refStyleOverflow = useRef<CSSStyleDeclaration["overflow"]>(
    typeof window !== 'undefined' ? window.getComputedStyle(document.body).overflow : ''
  );
  const { asPath } = useRouter();

  const openDialog = useCallback(() => {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    refDialog.current?.showModal();
    document.body.style.overflow = "hidden";
  }, []);

  const closeDialog = useCallback(() => {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    refDialog.current?.close();
    document.body.style.overflow = refStyleOverflow.current;
  }, []);

  const stopPropagation = useCallback(
    (e: React.MouseEvent<HTMLDivElement, MouseEvent>) => {
      e.stopPropagation();
    },
    []
  );

  const refHeader = useRef<HTMLElement>(null);

  useEffect(() => {
    initUnpinHeader(refHeader.current);
  }, []);

  useEffect(() => {
    closeDialog();
  }, [asPath, closeDialog]);

  return (
    <>
      <HeaderRoot ref={refHeader}>
        <HeaderContainer>
          <Link href="/" prefetch={false} passHref>
            <HeaderLogoAnchor>
              <Logo width="80" height="25" />
            </HeaderLogoAnchor>
          </Link>
          <HeaderSearchButton type="button" aria-label="Search" onClick={openDialog}>
            <HiSearch />
          </HeaderSearchButton>
        </HeaderContainer>
      </HeaderRoot>

      <Dialog ref={refDialog} onClick={closeDialog}>
        <div onClick={stopPropagation}>
          <Search />
        </div>
      </Dialog>
    </>
  );
};

const HeaderRoot = styled.header`
  position: fixed;
  z-index: var(--zIndex-header);
  top: 0;
  right: 0;
  left: 0;
  height: var(--header-height);
  margin: 0 auto;
  transition: transform 0.25s ease;
  pointer-events: none;
  will-change: transform;

  &.is-unpin {
    transform: translateY(calc(var(--header-height) * -1));
    box-shadow: none;
  }
`;

const HeaderContainer = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  max-width: var(--container-width);
  height: 100%;
  margin: 0 auto;
  transition: padding 0.1s ease-in-out;

  ${mobile} {
    padding: 0 5vw;
  }
`;

const HeaderLogoAnchor = styled.a`
  display: flex;
  align-items: center;
  height: 100%;
  pointer-events: auto;
`;

const HeaderSearchButton = styled.button`
  display: flex;
  align-items: center;
  justify-content: center;
  width: 3rem;
  height: 3rem;
  transition: background-color 0.2s ease;
  border: none;
  border-radius: 100%;
  background: none;
  cursor: pointer;
  pointer-events: auto;

  &:hover,
  &:focus {
    background-color: var(--component-backgrounds-4);
  }

  svg {
    width: 1.25rem;
    height: 1.25rem;
    color: var(--text-12);
  }
`;

const Dialog = styled.dialog`
  top: 10vh;
  padding: 0;
  border: none;
`

// components/common/TheHeader.vue
<template>
  <header class="pj-header js-header">
    <div class="o-container pj-header__container">
      <nuxt-link :title="siteName" to="/" class="pj-header__logo">
        <svgLogo class="pj-header__logo__icon" />
      </nuxt-link>
      <SearchInput />
    </div>
  </header>
</template>

<script>
import SearchInput from '~/components/SearchInput.vue';
import svgLogo from '~/assets/image/logo.svg?inline';

export default {
  name: 'TheHeader',
  components: {
    SearchInput,
    svgLogo,
  },
  data() {
    return {
      eleHeader: null,
      classes: {
        unpinned: 'is-unpin',
      },
      lastKnownScrollY: 0,
      ticking: false,
    };
  },
  computed: {
    siteName: () => process.env.SITE_NAME,
  },
  mounted: function() {
    this.eleHeader = document.querySelector('.js-header');
    document.addEventListener('scroll', this.handleScroll, !document.documentMode ? { passive: false } : false);
  },
  methods: {
    onScroll() {
      this.ticking = false;
      let currentScrollY = window.pageYOffset;
      if (this.lastKnownScrollY === currentScrollY || currentScrollY < 0) return;

      if (currentScrollY < this.lastKnownScrollY) {
        this.eleHeader.classList.remove(this.classes.unpinned);
      } else {
        this.eleHeader.classList.add(this.classes.unpinned);
      }

      this.lastKnownScrollY = currentScrollY;
    },
    handleScroll() {
      if (!this.ticking) {
        requestAnimationFrame(this.onScroll);
      }
      this.ticking = true;
    },
  },
};
</script>

<style lang="scss">
.pj-header {
  position: fixed;
  z-index: 10;
  top: 0;
  right: 0;
  left: 0;
  height: $header-height;
  transition: transform 0.25s ease;
  border-bottom: 1px solid map-get($light-color, 1);
  background: #fff;
  will-change: transform;

  &.is-unpin {
    transform: translateY(-$header-height);
    box-shadow: none;
  }
}

.pj-header__container {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 100%;
}

.pj-header__logo {
  display: flex;
  align-items: center;
  height: 100%;
  color: $color-text;

  &:hover {
    opacity: 0.6;
  }
}

.pj-header__logo__icon {
  width: 5rem;
  height: 100%;
  transition: width 0.2s;
  fill: $color-text;

  @include mobile {
    width: 4rem;
  }
}
</style>
