// components/PostPager.vue
<template>
  <nav v-if="Object.keys(pager).length !== 0" class="post-pager">
    <div class="pager-list">
      <router-link
        v-if="pager.prev"
        :to="pager.prev.url"
        :title="pager.prev.title"
        class="pager-item prev"
      >
        <div class="pager-icon">
          <svgArrowBack/>
        </div>
        <div class="pager-title">{{ pager.prev.title }}</div>
      </router-link>
      <router-link
        v-if="pager.next"
        :to="pager.next.url"
        :title="pager.next.title"
        class="pager-item next"
      >
        <div class="pager-icon">
          <svgArrowForward/>
        </div>
        <div class="pager-title">{{ pager.next.title }}</div>
      </router-link>
    </div>
  </nav>
</template>

<script>
import { mapState } from 'vuex';
import svgArrowBack from '~/assets/image/arrow_back.svg?inline';
import svgArrowForward from '~/assets/image/arrow_forward.svg?inline';

export default {
  name: 'PostPager',
  components: {
    svgArrowBack,
    svgArrowForward,
  },
  computed: {
    ...mapState('post', {
      pager: state => state.data.attach.pager,
    }),
  },
};
</script>

<style lang="scss">
.post-pager {
  margin: 2rem 0;
}

.pager-list {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  font-size: $font-size-sm;
}

.pager-item {
  display: grid;
  grid-column-gap: 0.5rem;
  width: 48%;
  padding: 1rem 0;
  border-radius: 0.15rem;
  color: $base-color;
  line-height: 1.8;
  word-break: break-all;

  &:hover {
    opacity: 0.6;
  }

  &:only-child {
    flex-grow: 1;
  }

  @include mobile {
    width: 100%;
  }

  &.prev {
    grid-template-columns: 1.5rem 1fr;
    text-align: left;
    .pager-icon {
      grid-row-start: 1;
      grid-column-start: 1;
    }
    .pager-title::before {
      content: 'Prev';
    }
  }
  &.next {
    grid-template-columns: 1fr 1.5rem;
    text-align: right;
    .pager-icon {
      grid-row-start: 1;
      grid-column-start: 2;
    }
    .pager-title::before {
      content: 'Next';
    }
  }

  .pager-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    svg {
      fill: $base-color;
    }
  }

  .pager-title {
    color: $base-color;
    &::before {
      display: block;
      font-weight: bold;
      color: $tertiary-color;
    }
  }
}
</style>

// components/PostPager.tsx
import styled from '@emotion/styled';
import Link from 'next/link';
import { FC } from 'react';
import { HiOutlineArrowLeft, HiOutlineArrowRight } from 'react-icons/hi';

import { mobile } from '@/lib/mediaQuery';
import { NextPrevPost } from '@/types/source';

type Props = {
  next: NextPrevPost;
  prev: NextPrevPost;
};

const PostPager: FC<Props> = ({ next, prev }) => {
  return (
    <PagerRoot>
      {Object.keys(prev).length !== 0 && (
        <Link href={`${prev.slug}.html`} prefetch={false} passHref>
          <PagerAnchorItem>
            <PagerIcon>
              <HiOutlineArrowLeft />
            </PagerIcon>
            <PagerMain>
              <div className="label">Prev</div>
              <div className="title">{prev.title}</div>
            </PagerMain>
          </PagerAnchorItem>
        </Link>
      )}
      {Object.keys(next).length !== 0 && (
        <Link href={`${next.slug}.html`} prefetch={false} passHref>
          <PagerAnchorItem>
            <PagerMain>
              <div className="label">Next</div>
              <div className="title">{next.title}</div>
            </PagerMain>
            <PagerIcon>
              <HiOutlineArrowRight />
            </PagerIcon>
          </PagerAnchorItem>
        </Link>
      )}
    </PagerRoot>
  );
};

export default PostPager;

const PagerRoot = styled.nav`
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  font-size: var(--font-size-sm);
`;

const PagerAnchorItem = styled.a`
  display: flex;
  align-items: flex-start;
  gap: 0.75rem;
  width: 50%;
  padding: 1rem;
  transition: background 0.2s ease, box-shadow 0.4s ease;
  border-radius: 0.25em;
  color: var(--color-text);
  line-height: 1.8;
  word-break: break-all;

  ${mobile} {
    width: 100%;
  }

  &:hover {
    background: var(--bg-color--lighter);
    box-shadow: 0 0 0 0.25rem var(--bg-color--lighter);
  }

  &:only-child {
    flex-grow: 1;
  }

  &:nth-child(2) {
    text-align: right;
  }
`;

const PagerMain = styled.div`
  flex-grow: 1;

  .label {
    color: var(--color-text--lighter);
    font-weight: bold;
    line-height: 1;
  }

  .title {
    margin-top: 0.5rem;
    color: var(--color-text);
  }
`;

const PagerIcon = styled.div`
  display: flex;
  align-items: center;
  height: 100%;
  color: var(--color-text--lighter);

  svg {
    width: 1rem;
    height: 1rem;
  }
`;
