// components/common/TheFooter.vue
<template>
  <footer>
    <div class="o-container">
      <div class="button-scrollTop" @click="scrollTop">
        <font-awesome-icon icon="arrow-up" />
      </div>
      <nav class="menu">
        <ul class="u-list-unstyled menu-list">
          <li class="menu-item">
            <nuxt-link to="/about">
              about
            </nuxt-link>
          </li>
          <li class="menu-item">
            <nuxt-link to="/archive">
              archive
            </nuxt-link>
          </li>
        </ul>
      </nav>
      <div class="copyright">
        <small>
          ©
          <nuxt-link to="/">{{ siteName }}</nuxt-link>
        </small>
      </div>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'TheFooter',
  computed: {
    siteName: () => process.env.SITE_NAME,
  },
  methods: {
    scrollTop: function() {
      window.scrollTo({
        top: 0,
        behavior: 'smooth',
      });
    },
  },
};
</script>

<style lang="scss" scoped>
footer {
  padding-top: 3rem;
  padding-bottom: 3rem;
  background: $base-color;
  color: map-get($light-color, 3);
  font-size: $font-size-sm;
  text-align: center;
  a:hover {
    text-decoration: underline;
  }
}

.button-scrollTop {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 1.5rem;
  cursor: pointer;

  svg {
    width: 1.5rem;
    height: 1.5rem;
    fill: map-get($light-color, 2);
  }
}

.copyright {
  small {
    font-size: 1em;
  }
  a {
    color: inherit;
  }
}
.menu {
  margin-bottom: 1rem;
}
.menu-list {
  display: inline-flex;
}
.menu-item {
  & + & {
    margin-left: map-get($size, sm) * 1rem;
  }
  a {
    color: map-get($light-color, 2);
  }
}
</style>

// components/TheFooter.tsx
import styled from '@emotion/styled';
import Link from 'next/link';
import { FC } from 'react';

const Footer = styled.footer`
  margin-top: calc(var(--margin-base) * 4);
  padding: 3rem 0;
  background: var(--bg-color--lighter);
  color: var(--color-text--light);
  line-height: 1;
  text-align: center;

  a {
    color: inherit;

    &:hover {
      text-decoration-line: underline;
    }
  }
`;

const FooterContainer = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  max-width: var(--container-width);
  margin: 0 auto;
  transition: padding 0.1s ease-in-out;

  @media (max-width: 959px) {
    padding: 0 5vw;
  }
`;

const FooterMeneList = styled.ul`
  display: inline-flex;
  padding: 0;
  list-style: none;
`;

const FooterMeneListItem = styled.li`
  & + & {
    margin-left: 1em;
  }
`;

const FooterCopyright = styled.div`
  small {
    font-size: 1em;
  }
`;

const TheFooter: FC = () => {
  return (
    <Footer>
      <FooterContainer>
        <FooterMeneList>
          <FooterMeneListItem>
            <Link href="/" prefetch={false}>
              <a>home</a>
            </Link>
          </FooterMeneListItem>
          <FooterMeneListItem>
            <Link href="/about" prefetch={false}>
              <a>about</a>
            </Link>
          </FooterMeneListItem>
          <FooterMeneListItem>
            <Link href="/archive" prefetch={false}>
              <a>archive</a>
            </Link>
          </FooterMeneListItem>
        </FooterMeneList>

        <FooterCopyright>
          <small>©&nbsp;hiro</small>
        </FooterCopyright>
      </FooterContainer>
    </Footer>
  );
};

export default TheFooter;
