// src/components/UI/TheFooter/index.tsx
import Link from 'next/link';

import { mobile } from '@/lib/mediaQuery';
import { styled } from '@/ui/styled';

export const TheFooter = () => (
  <Footer>
    <Container>
      <List role="list">
        <ListItem role="listitem">
          <Link href="/about" prefetch={false} passHref>
            <a>about</a>
          </Link>
        </ListItem>
        <ListItem role="listitem">
          <Link href="/archive" prefetch={false} passHref>
            <a>archive</a>
          </Link>
        </ListItem>
        <ListItem role="listitem">
          <Link href="/tags" prefetch={false} passHref>
            <a>tags</a>
          </Link>
        </ListItem>
      </List>
      <small>© hiro</small>
    </Container>
  </Footer>
);

const Footer = styled.footer`
  position: sticky;
  top: 100vh;
  margin-top: var(--space-x-xl);
  padding: var(--space-xl) 0;
  background-color: var(--component-backgrounds-3);
  color: var(--text-12);
  font-size: var(--font-size-sm);

  a {
    color: inherit;

    &:hover {
      text-decoration-line: underline;
    }
  }

  small {
    font-size: 1rem;
  }
`;

const Container = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  max-width: var(--container-width);
  margin: 0 auto;

  ${mobile} {
    padding: 0 5vw;
  }
`;

const List = styled.div`
  display: inline-flex;
`;

const ListItem = styled.div`
  display: inline-flex;

  & + & {
    margin-left: 1em;
  }
`;

// components/TheFooter.vue
<template>
  <footer>
    <div class="o-container">
      <nav class="menu">
        <ul class="u-list-unstyled menu-list">
          <li class="menu-item">
            <nuxt-link to="/about">
              about
            </nuxt-link>
          </li>
          <li class="menu-item">
            <nuxt-link to="/archive">
              archive
            </nuxt-link>
          </li>
        </ul>
      </nav>
      <div class="copyright">
        <small>
          ©
          <nuxt-link to="/">{{ siteName }}</nuxt-link>
        </small>
      </div>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'TheFooter',
  computed: {
    siteName: () => process.env.SITE_NAME,
  },
};
</script>

<style lang="scss" scoped>
footer {
  padding-bottom: 3rem;
  padding-top: 3rem;
  background: $secondary-color;
  color: map-get($light-color, 3);
  font-size: $font-size-sm;
  text-align: center;
  a:hover {
    text-decoration: underline;
  }
}
.copyright {
  small {
    font-size: 1em;
  }
  a {
    color: inherit;
  }
}
.menu {
  margin-bottom: 1rem;
}
.menu-list {
  display: inline-flex;
}
.menu-item {
  & + & {
    margin-left: map-get($size, sm) * 1rem;
  }
  a {
    color: map-get($light-color, 2);
  }
}
</style>
