// src/components/TheHeader.tsx
import { defineComponent, ref, computed, onMounted } from '@vue/composition-api';
import Search from './Search';
import CONSTANT from '~/constant';
// @ts-ignore
import svgLogo from '~/assets/image/logo.svg?raw';

export default defineComponent({
  name: 'TheHeader',
  setup() {
    const siteName = computed(() => CONSTANT.SITE_NAME);
    let ticking = false;
    let lastKnownScrollY = 0;

    onMounted(() => {
      const elHeader = document.querySelector('.js-header') as HTMLElement;
      const headerheight = elHeader.offsetHeight;

      document.addEventListener(
        'scroll',
        () => {
          handleScroll(elHeader, headerheight);
        },
        { passive: false },
      );
    });

    function handleScroll(elHeader: HTMLElement, headerheight: number) {
      if (!ticking) {
        requestAnimationFrame(() => {
          ticking = false;
          const currentScrollY = window.pageYOffset;

          // ヘッダーの高さを超えた場合
          if (currentScrollY >= headerheight) {
            if (currentScrollY <= lastKnownScrollY) {
              elHeader.classList.remove('is-unpin');
            } else {
              elHeader.classList.add('is-unpin');
            }
          } else {
            elHeader.classList.remove('is-unpin');
          }

          // 今回のスクロール位置を残す
          lastKnownScrollY = currentScrollY;
        });
      }

      ticking = true;
    }

    const showSearch = ref(false);

    function toggleModal() {
      document.body.classList.toggle('u-body-no-scroll', !showSearch.value);
      showSearch.value = !showSearch.value;
    }

    return {
      svgLogo,
      siteName,
      showSearch,
      toggleModal,
    };
  },
  render() {
    return (
      <header class="pj-header js-header">
        <div class="o-container pj-header-container">
          <nuxt-link title={this.siteName} to="/" class="pj-header__logo" domPropsInnerHTML={svgLogo} />
          <button type="button" class="pj-header-search" aria-label="Search" onClick={this.toggleModal}>
            <div class="pj-header-search__icon">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                <path
                  fillRule="evenodd"
                  d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                  clipRule="evenodd"
                />
              </svg>
            </div>
          </button>
        </div>
        <Search isOpen={this.showSearch} onDone={this.toggleModal} />
      </header>
    );
  },
});

// components/TheHeader.tsx
import Link from 'next/link';
import React, { useEffect } from 'react';

import Logo from '@/images/logo.svg';

const initUnpinHeader = () => {
  const elHeader = document.querySelector<HTMLDivElement>('.js-header');
  const headerHeight = elHeader.offsetHeight;
  const headerUnpinClassName = 'is-unpin';
  let ticking = false;
  let lastKnownScrollY = 0;

  const handleScroll = (elHeader: HTMLDivElement, headerHeight: number) => {
    if (!ticking) {
      requestAnimationFrame(() => {
        ticking = false;
        const currentScrollY = window.pageYOffset;

        // ヘッダーの高さを超えた場合
        if (currentScrollY >= headerHeight) {
          if (currentScrollY <= lastKnownScrollY) {
            elHeader.classList.remove(headerUnpinClassName);
          } else {
            elHeader.classList.add(headerUnpinClassName);
          }
        } else {
          elHeader.classList.remove(headerUnpinClassName);
        }

        // 今回のスクロール位置を残す
        lastKnownScrollY = currentScrollY;
      });
    }

    ticking = true;
  };

  document.addEventListener(
    'scroll',
    () => {
      handleScroll(elHeader, headerHeight);
    },
    { passive: false },
  );
};

const TheHeader = () => {
  useEffect(() => {
    initUnpinHeader();
  });

  return (
    <header className="pj-header js-header">
      <div className="l-container pj-header-container">
        <Link href="/">
          <a className="pj-header__logo">
            <Logo width="5rem" />
          </a>
        </Link>
      </div>
    </header>
  );
};

export default TheHeader;
