// components/TheFooter.tsx
import Link from 'next/link';

import Logo from '@/images/logo.svg';

const TheFooter = () => {
  return (
    <footer className="pj-footer">
      <div className="l-container">
        <div className="pj-footer__logo">
          <Link href="/">
            <a>
              <Logo />
            </a>
          </Link>
        </div>
        <div className="pj-footer-menu">
          <ul className="u-list-unstyled pj-footer-menu__list">
            <li className="pj-footer-menu__item">
              <Link href="/about">
                <a className="pj-footer__link">about</a>
              </Link>
            </li>
            <li className="pj-footer-menu__item">
              <Link href="/archive">
                <a className="pj-footer__link">archive</a>
              </Link>
            </li>
            <li className="pj-footer-menu__item">
              <a href="/rss.xml" className="pj-footer__link" target="_blank">
                feed
              </a>
            </li>
          </ul>
        </div>

        <div className="pj-footer-copyright">
          <small className="pj-footer-copyright__text">©&nbsp;hiro</small>
        </div>
      </div>
    </footer>
  );
};

export default TheFooter;

// src/components/TheFooter.tsx
import { defineComponent } from '@nuxtjs/composition-api';

import svgLogo from '~/assets/image/logo.svg?raw';
import CONSTANT from '~/constant';

export default defineComponent({
  name: 'TheFooter',
  setup() {
    return {};
  },
  render() {
    return (
      <footer class="pj-footer">
        <div class="o-container">
          <div class="pj-footer__logo">
            <router-link to="/" title={CONSTANT.SITE_NAME} domPropsInnerHTML={svgLogo} />
          </div>
          <div class="pj-footer-menu">
            <ul class="u-list-unstyled pj-footer-menu__list">
              <li class="pj-footer-menu__item">
                <router-link to="/about" class="pj-footer__link">
                  about
                </router-link>
              </li>
              <li class="pj-footer-menu__item">
                <router-link to="/archive" class="pj-footer__link">
                  archive
                </router-link>
              </li>
              <li class="pj-footer-menu__item">
                <a href="/rss.xml" class="pj-footer__link" target="_blank">
                  feed
                </a>
              </li>
            </ul>
          </div>

          <div class="pj-footer-copyright">
            <small class="pj-footer-copyright__text">©&nbsp;hiro</small>
          </div>
        </div>
      </footer>
    );
  },
});
