// pages/about.tsx
import { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

import Heading from '@/components/Heading';
import { Container } from '@/components/layout/Container';
import { SITE } from '@/constant';
import { getPagesJson } from '@/lib/posts';
import { Pages } from '@/types/source';

interface Props {
  page: Pages;
}

const About: NextPage<Props> = ({ page }) => {
  return (
    <>
      <Head>
        <title key="title">サイトについて - {SITE.NAME}</title>
      </Head>

      <Container>
        <article className="p-post">
          <header>
            <Heading text={'About'} />
          </header>

          <div
            className="p-post__content"
            dangerouslySetInnerHTML={{
              __html: `${page.content}`,
            }}
          />
        </article>
      </Container>
    </>
  );
};

export default About;

export const getStaticProps: GetStaticProps = async () => {
  const pages = getPagesJson();
  const page = pages.find((page) => page.slug === 'about');

  return {
    props: {
      page,
    },
  };
};

// pages/about/index.vue
<template>
  <article class="about">
    <header class="c-heading--large">
      <h1 class="c-heading__title">
        {{ pageTitle }}
      </h1>
    </header>
    <LayoutArticle :class-name="'about'">
      <div class="post-content">
        <ul>
          <li>
            <nuxt-link to="about/me">
              運営者について
            </nuxt-link>
          </li>
          <li>
            <nuxt-link to="about/site">
              サイトについて
            </nuxt-link>
          </li>
        </ul>
      </div>
    </LayoutArticle>
  </article>
</template>

<script>
const LayoutArticle = () => import('~/components/LayoutArticle.vue');

export default {
  name: 'About',
  head() {
    return {
      title: this.pageTitle,
    };
  },
  components: {
    LayoutArticle,
  },
  computed: {
    pageTitle: () => 'about',
  },
};
</script>
