// src/pages/about.vue
<template>
  <article class="post">
    <LayoutHeader>
      <template v-slot:header-title>
        {{ pageTitle }}
      </template>
      <template v-slot:header-description>
        {{ pageDescription }}
      </template>
    </LayoutHeader>
    <div class="post__content js-post-content" v-html="page.content" />
  </article>
</template>

<script type="ts">
import { defineComponent, computed } from '@vue/composition-api';

export default defineComponent({
  name: 'About',
  asyncData({ app }) {
    const page = app.$source.pages.find((page) => page.slug === 'about');

    return {
      page: {
        ...page,
        content: app.$filteredPost(page.content),
      },
    };
  },
  setup(_) {
    const pageTitle = computed(() => 'About');
    const pageDescription = computed(() => 'サイトと運営者の情報');

    return {
      pageTitle,
      pageDescription,
    };
  },
  head() {
    return {
      title: this.pageTitle,
      meta: [{ hid: 'description', name: 'description', content: this.pageDescription }],
    };
  },
});
</script>

// pages/about.tsx
import { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

import Heading from '@/components/Heading';
import { Container } from '@/components/layout/Container';
import { SITE } from '@/constant';
import { getPagesJson } from '@/lib/posts';
import { Pages } from '@/types/source';

interface Props {
  page: Pages;
}

const About: NextPage<Props> = ({ page }) => {
  return (
    <>
      <Head>
        <title key="title">サイトについて - {SITE.NAME}</title>
      </Head>

      <Container>
        <article className="p-post">
          <header>
            <Heading text={'About'} />
          </header>

          <div
            className="p-post__content"
            dangerouslySetInnerHTML={{
              __html: `${page.content}`,
            }}
          />
        </article>
      </Container>
    </>
  );
};

export default About;

export const getStaticProps: GetStaticProps = async () => {
  const pages = getPagesJson();
  const page = pages.find((page) => page.slug === 'about');

  return {
    props: {
      page,
    },
  };
};
