// src/pages/about.tsx
import { defineComponent, useAsync, useMeta } from '@nuxtjs/composition-api';

import LayoutHeader from '~/components/LayoutHeader';
import { Pages } from '~/types/source';

const pages: Array<Pages> = require('~/_source/pages.json');

const pageTitle = 'About';
const pageDescription = 'サイトと運営者の情報';

export default defineComponent({
  name: 'About',
  setup() {
    useMeta({
      title: pageTitle,
      meta: [{ hid: 'description', name: 'description', content: pageDescription }],
    });

    const content = useAsync(() => {
      const page = pages.find((page: any) => page.slug === 'about');

      // @ts-ignore
      return page.content;
    });

    return {
      content,
    };
  },
  head() {
    return {};
  },
  render() {
    return (
      <article class="post">
        <LayoutHeader heading={pageTitle} description={pageDescription} />
        <div class="post__content js-post-content" domPropsInnerHTML={this.content} />
      </article>
    );
  },
});

// pages/about.tsx
import fs from 'fs-extra';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import path from 'path';

import Layout from '@/components/Layout';
import { SITE } from '@/constant';
import { Pages } from '@/types/source';

interface Props {
  page: Pages;
}

const About = ({ page }: Props) => {
  return (
    <>
      <Head>
        <title key="title">サイトについて - {SITE.NAME}</title>
      </Head>

      <Layout>
        <article className="p-post">
          <header className="l-section-header">
            <h1 className="c-heading">{page.title}</h1>
          </header>

          <div
            className="p-post__content"
            dangerouslySetInnerHTML={{
              __html: `${page.content}`,
            }}
          />
        </article>
      </Layout>
    </>
  );
};

export default About;

export const getStaticProps: GetStaticProps = async () => {
  const dataPath = path.join(process.cwd(), '_source/pages.json');
  const pages: Array<Pages> = fs.readJsonSync(dataPath);
  const postData = pages.find((page) => page.slug === 'about');

  return {
    props: {
      page: postData,
    },
  };
};
