// pages/archive.vue
<template>
  <article class="archive">
    <LayoutHeader>
      <template v-slot:header-title>
        {{ pageTitle }}
      </template>
      <template v-slot:header-description>
        {{ pageDescription }}
      </template>
    </LayoutHeader>
    <section>
      <div v-for="(archive, yaer) in archives" :key="yaer" class="archive-list">
        <div class="archive-year">
          <h2 class="archive-year__title">{{ yaer }}</h2>
        </div>
        <div class="archive-post">
          <div v-for="(post, index) in archive" :key="index" class="archive-post-list">
            <a :href="post.path" class="archive-post-item">
              <div class="archive-post-item__title">{{ post.title }}</div>
              <time :datetime="post.date" class="archive-post-item__date">{{
                convertDateToSimpleFormat(post.date)
              }}</time>
            </a>
          </div>
        </div>
      </div>
    </section>
  </article>
</template>

<script type="ts">
import { defineComponent, computed } from '@vue/composition-api';
import { convertDateToSimpleFormat } from '~/assets/script/utils/date.ts';

const formatArchive = (srcArchives) => {
  const archives = {};

  for (let i = 0; i < srcArchives.length; i++) {
    const post = srcArchives[i];

    // 日付を取得する
    const date = new Date(post.date);
    const year = date.getFullYear();

    // 配列で初期化
    if (!Array.isArray(archives[year])) {
      archives[year] = [];
    }

    archives[year].push(post);
  }

  return archives;
};

export default defineComponent({
  name: 'Archive',
  setup(_, { root }) {
    const pageTitle = computed(() => 'Archive');
    const pageDescription = computed(() => 'これまでに公開した記事の一覧です。');
    const archives = computed(() => formatArchive(root.$source.archives));

    return {
      pageTitle,
      pageDescription,
      convertDateToSimpleFormat,
      archives,
    };
  },
  head() {
    return {
      title: this.pageTitle,
      meta: [{ hid: 'description', name: 'description', content: this.pageDescription }],
    };
  },
});
</script>

// pages/archive.tsx
import fs from 'fs-extra';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import path from 'path';

import HoverCard from '@/components/HoverCard';
import PageContainer from '@/components/layout/PageContainer';
import { SITE } from '@/constant';
import { Archives } from '@/types/source';

interface Props {
  archives: Array<Archives>;
}

const divideByYearArchive = (archives: Array<Archives>) => {
  const formatArchives = {};

  for (let i = 0; i < archives.length; i++) {
    const post = archives[i];

    // 日付を取得する
    const date = new Date(post.date);
    const year = date.getFullYear().toString() + ' ';

    // 配列で初期化
    if (!Array.isArray(formatArchives[year])) {
      formatArchives[year] = [];
    }

    formatArchives[year].push(post);
  }

  return formatArchives;
};

const Archive = ({ archives }: Props) => {
  const posts = divideByYearArchive(archives);

  return (
    <>
      <Head>
        <title key="title">Archive - {SITE.NAME}</title>
      </Head>

      <PageContainer>
        <article className="p-archive">
          <header className="l-section-header">
            <h1 className="c-heading">Archive</h1>
          </header>

          <section className="p-archive__contents">
            {Object.keys(posts).map((key: string) => {
              return (
                <div key={key} className="archive-list">
                  <div className="archive-year">
                    <h2 className="archive-year__title">{key}</h2>
                  </div>
                  <ul className="archive-post">
                    {posts[key].map((post: Archives, index: number) => {
                      return (
                        <li key={index}>
                          <HoverCard
                            link={'/' + post.path}
                            title={post.title}
                            date={post.date}
                            excerpt={post.excerpt}
                          />
                        </li>
                      );
                    })}
                  </ul>
                </div>
              );
            })}
          </section>
        </article>
      </PageContainer>
    </>
  );
};

export default Archive;

export const getStaticProps: GetStaticProps = async () => {
  const dataPath = path.join(process.cwd(), '_source/archives.json');
  const posts: Array<Archives> = fs.readJsonSync(dataPath);

  return {
    props: {
      archives: posts,
    },
  };
};
