// src/components/UI/Tag/index.tsx
import { memo } from 'react';

import { Anchor as _Anchor } from '@/components/UI/Anchor';
import { styled } from '@/ui/styled';

export type Props = {
  slug: string;
  count?: number;
};

type PostTagProps = {
  tags: Props[];
};

const PostTag = memo(function PostTag({ tags }: PostTagProps) {
  if (tags?.length === 0) {
    return null;
  }

  return (
    <>
      {tags?.map(({ slug, count }) => (
        <Anchor
          href={'/tags/' + slug}
          prefetch={false}
          passHref
          key={slug}
          title={count ? `${slug}: ${count}件` : 'tag: ' + slug}
        >
          {slug}
        </Anchor>
      ))}
    </>
  );
});

export default PostTag;

export const PostTagGridContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-1);
`;

const Anchor = styled(_Anchor)`
  flex: 1 1 auto;
  align-items: center;
  align-self: flex-start;
  padding: var(--space-1);
  line-height: 1;
  color: var(--text-11);
  text-align: center;
  white-space: nowrap;
  background-color: var(--component-backgrounds-4A);
  border-radius: var(--border-radius-4);

  &:hover {
    background-color: var(--component-backgrounds-5A);
  }

  &::before {
    content: '#';
  }
`;

// pages/tag/index.vue
<template>
  <section>
    <div class="c-title">
      <h1 class="title-main">{{ pageTitle }}</h1>
    </div>
    <ul class="u-list-unstyled tag-list">
      <li v-for="(tag, index) in tagList" :key="index" class="tag-item">
        <nuxt-link :to="'/tag/' + tag.slug">{{ tag.name }}</nuxt-link>
      </li>
    </ul>
  </section>
</template>

<script>
export default {
  name: 'TagList',
  head() {
    return {
      title: this.pageTitle,
    };
  },
  data() {
    return {
      tagList: {},
    };
  },
  computed: {
    pageTitle: () => 'Tag List',
  },
  async mounted() {
    this.tagList = (await this.$axios.get('wp/v2/tags', {
      params: {
        order: 'desc',
        orderby: 'count',
        per_page: 100,
      },
    })).data;
  },
};
</script>

<style lang="scss">
.tag-list {
  display: flex;
  flex-wrap: wrap;
  margin: 0 0 2rem 0.25rem;
}

.tag-item {
  margin-left: 0.25rem;
  margin-bottom: 0.5rem;
  flex: 1 1 auto;
  align-items: center;
  align-self: flex-start;
  white-space: nowrap;
  text-align: center;

  a {
    display: block;
    padding: 0.5em 1em;
    border-radius: 0.15rem;
    line-height: 1.5;
    background-color: $oc-gray-1;
    color: $oc-gray-8;
    font-size: map-get($size, sm) * 1rem;

    &:hover {
      background-color: $oc-gray-2;
    }
  }
}
</style>
